### ISSUE TITLE
[Feature] Entity 코드 작성

### ISSUE THREAD

**Issue by EBEL21** [EBEL21/steadybucks-be#2]
### TO-DO
- [x] 1. 다음 entity에 대한 코드 추가: User, Clan, Account, Interest, Stock
- [x] 2. Join Relation 설계
- [x] 3. Check Database Schema is valid
